### ISSUE TITLE
New helm chart

### ISSUE THREAD

**Issue by mikkeschiren** [directus-labs/helm-chart#17]
While waiting to learn the future of this community chart, which we want to contribute to, we created our own chart, based on this, with some fixes and more configuration options.

You can find this chart here:
https://github.com/digitalist-se/directus-helm-chart

Our hope is to contribute back to this chart if we get permission to do so. It's better with one great chart, then several random companies building their own.

**Comment by meezaan** [comment]
@mikkeschiren have you requested permission from the Directus team?

**Comment by mikkeschiren** [comment]
@meezaan - yes.

**Comment by meezaan** [comment]
> yes.

On Discord?

**Comment by mikkeschiren** [comment]
We have been talking, on Discord and email. But no movement.

**Comment by meezaan** [comment]
> We have been talking, on Discord and email. But no movement.

I've asked for help. Will keep you posted.

**Comment by meezaan** [comment]
> We have been talking, on Discord and email. But no movement.

I'm told you have been invited / given access. Can you please confirm? Thank you.

**Comment by mikkeschiren** [comment]
I just got access, thank you :) 
I will look into the differences in the charts, and add some pull requests.
