### ISSUE TITLE
Helm chart currently unavailable

### ISSUE THREAD

**Issue by me-marcel** [directus-labs/helm-chart#20]
The `index.yaml` (maybe even all the files) for the Helm repository which was originally located at at https://directus-community.github.io/helm-chart/index.yaml has magically vanished. Thus no deployments are currently possible using the community chart.

Are there any plans to revive this?

**Comment by me-marcel** [comment]
I've been looking into the most recent deployment and it seems as if the most recent deployment three days ago published the Chart under a new path at: https://directus-labs.github.io/helm-chart/ It seems like proper documentation was forgotten. It could be possible that the organization name changed between the past two deployments which caused this undocumented change.

@meezaan Would you mind changing the README.md file accordingly?

**Comment by meezaan** [comment]
I'll try and have a look this week.

**Comment by me-marcel** [comment]
@meezaan Any updates?

**Comment by meezaan** [comment]
@me-marcel I've updated the chart and the builds now work but there are still a couple of PRs to go.

**Comment by me-marcel** [comment]
Looks good!
