### ISSUE TITLE
Repo Contributors & Maintainership

### ISSUE THREAD

**Issue by phazonoverload** [directus-labs/helm-chart#22]
Hi all, I'm part of the Developer Experience team here at Directus, and as others have noticed - this repo is a bit quiet. It isn't one we officially maintain and without much time to spend on it, it's looking a bit sad. 

I wanted to put a call out to formally involve some community members as formal contributors to increase the longevity of this project. 

Please let us know in comments if you are interested. Just another 1 or 2 people feels viable. I'll leave this over the weekend and get back to it next week.

**Comment by phazonoverload** [comment]
@mikkeschiren and @mikesindieiev - sorry to tall you out by name but you are two more active community members in this repo. Zero pressure or expectation, but wanted to make sure you saw it.

**Comment by mikkeschiren** [comment]
Hi, for me it is important that it is really a community project, not just one or two contributors, I would engage if people get engaged :)

**Comment by phazonoverload** [comment]
What I mean more by this is 1 or 2 people to lead the charge. I would still love others to be involved, but right now there's no one to actually take the energy people want to give and direct it anywhere.

**Comment by mikesindieiev** [comment]
Fully agree with @mikkeschiren. It is not a big deal for me to maintain/contribute to the helm chart in my spare time

**Comment by phazonoverload** [comment]
Ok lovely - you're both added as contributors with maintainer rights. We trust you to do as you see fit with this repo, including using the tools provided by GitHub (like Discussions, if desired).

The only thing I ask is the note at the top of the README stays there.
