### ISSUE TITLE
Deprecated HPA API version

### ISSUE THREAD

**Issue by me-marcel** [directus-labs/helm-chart#29]
**Problem:**

The template for the `HorizontalPodAutoscaler` located at https://github.com/directus-labs/helm-chart/blob/master/charts/directus/templates/hpa.yaml uses an outdated API version. `v2beta1` has been deprecated since Kubernetes `v1.22` and has been finally removed with the release of `v1.25` rendering the template practically useless. With modern clusters the autoscaling feature cannot be used.

---
**Solution:**

I suggest the usage of the API `autoscaling/v2` within the charts HPA template file.

**Comment by mikesindieiev** [comment]
Hello! Feel free to open a PR. I'll take a look
